[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spock"
version = "1.6.0"
description = "Stability of Planetary Orbital Configurations Klassifier"
readme = "README.md"
readme-content-type = "text/markdown"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
    {name = "Daniel Tamayo", email = "tamayo.daniel@gmail.com"}
]
keywords = ["astronomy", "astrophysics", "exoplanets", "stability"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Scientific/Engineering :: Astronomy",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3"
]
dependencies = [
    "rebound>=3.14.0",           # classifier regressor analytical
    "scikit-learn",              # classifier regressor
    "xgboost>=1.1.0",            # classifier 
    "matplotlib",                #            regressor
    "pytorch_lightning>=1.0.0",  #            regressor
    "torch>=1.5.1",              #            regressor
    "torchvision",               #            regressor
    "scipy",                     #            regressor
    "einops",                    #            regressor
    "numpy",                     #            regressor analytical
    "pandas",                    #            regressor
    "celmech"                    #                      analytical
]

[project.urls]
Homepage = "https://github.com/dtamayo/spock"

[tool.setuptools.package-data]
"spock" = [
    "models/featureclassifier.json",
    "models/regression/steps=300000*.pkl"
]

[tool.setuptools]
test_suite = "spock.test"
zip_safe = false
