name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - '3.12'
          - '3.9'

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: "Install spock"
        run: |
            python -m pip install --upgrade pip
            pip install .[test]
      - name: "Run tests"
        run: python -m unittest discover
        continue-on-error: true
        # TODO: fix tests
