name: SPOCK (ipynbs)

on: [push, pull_request]

jobs:
  test_ipynb:
    name: Test ipynbs on ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 30

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12", "3.9"]
        os: [ubuntu-latest, macos-14]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: "Install SPOCK"
        run: |
            python -m pip install --upgrade pip
            pip install .[test]
      - name: Running jupyter notebooks
        run: |
          cd jupyter_examples
          python ipynb2py.py ComparingToNbody.ipynb
          python ipynb2py.py GridOfStabilityPredictions.ipynb
          python ipynb2py.py QuickStart.ipynb
